[package]
name = "burn-onnx-runner"
version = "0.1.0"
edition = "2024"

[workspace]

[dependencies]
burn = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std", "flex"], rev = "3bf6e039482de4e0cb68fc370d4c4e48b767a737" }
burn-store = { git = "https://github.com/tracel-ai/burn", default-features = false, features = ["std"], rev = "3bf6e039482de4e0cb68fc370d4c4e48b767a737" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[profile.release]
opt-level = 1
debug = false
