//! Opset 22 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn acos() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "acos");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Acos(
        AcosNode {
            name: "acos1",
            inputs: [
                Argument {
                    name: "acos_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "acos1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn acosh() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "acosh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Acosh(
        AcoshNode {
            name: "acosh1",
            inputs: [
                Argument {
                    name: "acosh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "acosh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn asin() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "asin");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Asin(
        AsinNode {
            name: "asin1",
            inputs: [
                Argument {
                    name: "asin_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "asin1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn asinh() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "asinh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Asinh(
        AsinhNode {
            name: "asinh1",
            inputs: [
                Argument {
                    name: "asinh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "asinh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn atan() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "atan");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Atan(
        AtanNode {
            name: "atan1",
            inputs: [
                Argument {
                    name: "atan_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "atan1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn atanh() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "atanh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Atanh(
        AtanhNode {
            name: "atanh1",
            inputs: [
                Argument {
                    name: "atanh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "atanh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn average_pool() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "averagepool2d");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    AveragePool2d(
        AveragePool2dNode {
            name: "averagepool2d1",
            inputs: [
                Argument {
                    name: "averagepool_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "averagepool2d1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: AvgPool2dConfig {
                kernel_size: [
                    2,
                    2,
                ],
                strides: [
                    2,
                    2,
                ],
                padding: Valid,
                count_include_pad: false,
                dilation: [
                    1,
                    1,
                ],
                ceil_mode: false,
                auto_pad: NotSet,
            },
        },
    )
    "#);
}

#[test]
fn bernoulli() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "bernoulli");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Bernoulli(
        BernoulliNode {
            name: "bernoulli1",
            inputs: [
                Argument {
                    name: "bernoulli_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "bernoulli1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn conv() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "conv2d");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Conv2d(
        Conv2dNode {
            name: "conv2d1",
            inputs: [
                Argument {
                    name: "conv_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        5,
                                    ),
                                    Some(
                                        5,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "conv2d1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: Conv2dConfig {
                kernel_size: [
                    3,
                    3,
                ],
                stride: [
                    1,
                    1,
                ],
                padding: Valid,
                dilation: [
                    1,
                    1,
                ],
                groups: 1,
                auto_pad: NotSet,
            },
        },
    )
    "#);
}

#[test]
fn conv_transpose() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "convtranspose2d");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ConvTranspose2d(
        ConvTranspose2dNode {
            name: "convtranspose2d1",
            inputs: [
                Argument {
                    name: "convtranspose_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        5,
                                    ),
                                    Some(
                                        5,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "convtranspose2d1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        5,
                                    ),
                                    Some(
                                        5,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ConvTranspose2dConfig {
                kernel_size: [
                    3,
                    3,
                ],
                stride: [
                    1,
                    1,
                ],
                dilation: [
                    1,
                    1,
                ],
                padding: [
                    0,
                    0,
                ],
                padding_out: [
                    0,
                    0,
                ],
                groups: 1,
            },
        },
    )
    "#);
}

#[test]
fn cos() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "cos");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Cos(
        CosNode {
            name: "cos1",
            inputs: [
                Argument {
                    name: "cos_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "cos1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn cosh() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "cosh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Cosh(
        CoshNode {
            name: "cosh1",
            inputs: [
                Argument {
                    name: "cosh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "cosh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn deform_conv() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "deformconv");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    DeformConv(
        DeformConvNode {
            name: "deformconv1",
            inputs: [
                Argument {
                    name: "deformconv_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        2,
                    ),
                },
                Argument {
                    name: "deformconv_offset",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "deformconv1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: DeformConvConfig {
                kernel_size: [
                    2,
                    2,
                ],
                stride: [
                    1,
                    1,
                ],
                padding: Valid,
                dilation: [
                    1,
                    1,
                ],
                groups: 1,
                offset_groups: 1,
            },
        },
    )
    "#);
}

/// Dropout is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn dropout() {
    let _graph = load_model("opset_22.onnx");
}

#[test]
fn elu() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "elu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Elu(
        EluNode {
            name: "elu1",
            inputs: [
                Argument {
                    name: "elu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "elu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: EluConfig {
                alpha: 1.0,
            },
        },
    )
    "#);
}

#[test]
fn eye_like() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "eyelike");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    EyeLike(
        EyeLikeNode {
            name: "eyelike1",
            inputs: [
                Argument {
                    name: "eyelike_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "eyelike1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: EyeLikeConfig {
                dtype: None,
                k: 0,
            },
        },
    )
    "#);
}

#[test]
fn gru() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "gru");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Gru(
        GruNode {
            name: "gru1",
            inputs: [
                Argument {
                    name: "gru_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        5,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        6,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "gru1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: GruConfig {
                input_size: 3,
                hidden_size: 4,
                direction: Forward,
                has_bias: false,
                has_initial_h: false,
                batch_first: false,
                clip: None,
                linear_before_reset: false,
                gate_activation: Sigmoid,
                hidden_activation: Tanh,
                activation_alpha: None,
                activation_beta: None,
            },
        },
    )
    "#);
}

#[test]
fn global_average_pool() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "globalaveragepool");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    GlobalAveragePool(
        GlobalAveragePoolNode {
            name: "globalaveragepool1",
            inputs: [
                Argument {
                    name: "globalaveragepool_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "globalaveragepool1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn grid_sample() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "gridsample");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    GridSample(
        GridSampleNode {
            name: "gridsample1",
            inputs: [
                Argument {
                    name: "gridsample_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "gridsample_grid",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "gridsample1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: GridSampleConfig {
                mode: Bilinear,
                padding_mode: Zeros,
                align_corners: false,
            },
        },
    )
    "#);
}

#[test]
fn hard_sigmoid() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "hardsigmoid");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    HardSigmoid(
        HardSigmoidNode {
            name: "hardsigmoid1",
            inputs: [
                Argument {
                    name: "hardsigmoid_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "hardsigmoid1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: HardSigmoidConfig {
                alpha: 0.2,
                beta: 0.5,
            },
        },
    )
    "#);
}

#[test]
fn hard_swish() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "hardswish");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    HardSwish(
        HardSwishNode {
            name: "hardswish1",
            inputs: [
                Argument {
                    name: "hardswish_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "hardswish1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn instance_normalization() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "instancenormalization");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    InstanceNormalization(
        InstanceNormalizationNode {
            name: "instancenormalization1",
            inputs: [
                Argument {
                    name: "instancenormalization_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        7,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        8,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "instancenormalization1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: InstanceNormConfig {
                epsilon: 9.999999747378752e-6,
            },
        },
    )
    "#);
}

#[test]
fn lstm() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "lstm");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Lstm(
        LstmNode {
            name: "lstm1",
            inputs: [
                Argument {
                    name: "lstm_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        16,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        9,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        16,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        10,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "lstm1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: LstmConfig {
                input_size: 3,
                hidden_size: 4,
                direction: Forward,
                has_bias: false,
                has_initial_h: false,
                has_initial_c: false,
                has_peephole: false,
                batch_first: false,
                clip: None,
                input_forget: false,
                gate_activation: Sigmoid,
                cell_activation: Tanh,
                hidden_activation: Tanh,
            },
        },
    )
    "#);
}

#[test]
fn max_pool() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "maxpool2d");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    MaxPool2d(
        MaxPool2dNode {
            name: "maxpool2d1",
            inputs: [
                Argument {
                    name: "maxpool_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "maxpool2d1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: MaxPool2dConfig {
                kernel_size: [
                    2,
                    2,
                ],
                strides: [
                    2,
                    2,
                ],
                padding: Valid,
                dilation: [
                    1,
                    1,
                ],
                ceil_mode: false,
                auto_pad: NotSet,
            },
        },
    )
    "#);
}

#[test]
fn mish() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "mish");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Mish(
        MishNode {
            name: "mish1",
            inputs: [
                Argument {
                    name: "mish_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "mish1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn random_normal() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "randomnormal");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    RandomNormal(
        RandomNormalNode {
            name: "randomnormal1",
            inputs: [],
            outputs: [
                Argument {
                    name: "randomnormal1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: RandomNormalConfig {
                mean: 0.0,
                scale: 1.0,
                shape: [
                    2,
                    3,
                ],
            },
        },
    )
    "#);
}

#[test]
fn random_normal_like() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "randomnormallike");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    RandomNormalLike(
        RandomNormalLikeNode {
            name: "randomnormallike1",
            inputs: [
                Argument {
                    name: "randomnormallike_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "randomnormallike1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: RandomNormalLikeConfig {
                mean: 0.0,
                scale: 1.0,
            },
        },
    )
    "#);
}

#[test]
fn random_uniform() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "randomuniform");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    RandomUniform(
        RandomUniformNode {
            name: "randomuniform1",
            inputs: [],
            outputs: [
                Argument {
                    name: "randomuniform1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: RandomUniformConfig {
                low: 0.0,
                high: 1.0,
                shape: [
                    2,
                    3,
                ],
            },
        },
    )
    "#);
}

#[test]
fn random_uniform_like() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "randomuniformlike");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    RandomUniformLike(
        RandomUniformLikeNode {
            name: "randomuniformlike1",
            inputs: [
                Argument {
                    name: "randomuniformlike_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "randomuniformlike1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: RandomUniformLikeConfig {
                low: 0.0,
                high: 1.0,
            },
        },
    )
    "#);
}

#[test]
fn round() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "round");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Round(
        RoundNode {
            name: "round1",
            inputs: [
                Argument {
                    name: "round_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "round1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn selu() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "selu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Selu(
        SeluNode {
            name: "selu1",
            inputs: [
                Argument {
                    name: "selu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "selu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: SeluConfig {
                alpha: 1.6732631921768188,
                gamma: 1.0507010221481323,
            },
        },
    )
    "#);
}

#[test]
fn sin() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "sin");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Sin(
        SinNode {
            name: "sin1",
            inputs: [
                Argument {
                    name: "sin_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "sin1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn sinh() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "sinh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Sinh(
        SinhNode {
            name: "sinh1",
            inputs: [
                Argument {
                    name: "sinh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "sinh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn softplus() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "softplus");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Softplus(
        SoftplusNode {
            name: "softplus1",
            inputs: [
                Argument {
                    name: "softplus_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "softplus1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn softsign() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "softsign");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Softsign(
        SoftsignNode {
            name: "softsign1",
            inputs: [
                Argument {
                    name: "softsign_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "softsign1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn tan() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "tan");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Tan(
        TanNode {
            name: "tan1",
            inputs: [
                Argument {
                    name: "tan_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "tan1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn thresholded_relu() {
    let graph = load_model("opset_22.onnx");
    let node = find_node(&graph, "thresholdedrelu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ThresholdedRelu(
        ThresholdedReluNode {
            name: "thresholdedrelu1",
            inputs: [
                Argument {
                    name: "thresholdedrelu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "thresholdedrelu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ThresholdedReluConfig {
                alpha: 1.0,
            },
        },
    )
    "#);
}
