//! Opset 24 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_24.onnx")
}

#[rstest]
fn attention(graph: &OnnxGraph) {
    let node = find_node(graph, "attention");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Attention "attention1"
      Inputs:
        attention_q: F32[1, 2, 3, 4]
        attention_k: F32[1, 2, 5, 4]
        attention_v: F32[1, 2, 5, 4]
      Outputs:
        attention1_out1: F32[?, ?, ?, ?]
      Config:
        AttentionConfig {
            is_causal: false,
            kv_num_heads: None,
            q_num_heads: None,
            qk_matmul_output_mode: Matmul,
            scale: None,
            softcap: 0.0,
            softmax_precision: None,
        }
    "#);
}

#[rstest]
fn cast(graph: &OnnxGraph) {
    let node = find_node(graph, "cast");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Cast "cast1"
      Inputs:
        cast_input: F32[2, 3]
      Outputs:
        cast1_out1: I32[2, 3]
      Config:
        CastConfig {
            to: I32,
        }
    "#);
}

#[rstest]
fn cast_like(graph: &OnnxGraph) {
    let node = find_node(graph, "castlike");
    insta::assert_snapshot!(format!("{node}"), @r#"
    CastLike "castlike1"
      Inputs:
        castlike_input: F32[2, 3]
      Outputs:
        castlike1_out1: I32[2, 3]
      Config:
        CastLikeConfig {
            to: I32,
            saturate: None,
            round_mode: None,
        }
    "#);
}

#[rstest]
fn constant(graph: &OnnxGraph) {
    let node = find_graph_output_node(graph, "constant");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Constant "constant14"
      Inputs:
        _: F32[2, 3] [static(13)]
      Outputs:
        constant14_out1: F32[2, 3] [constant]
    "#);
}

#[rstest]
fn constant_of_shape(graph: &OnnxGraph) {
    let node = find_node(graph, "constantofshape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ConstantOfShape "constantofshape1"
      Inputs:
        _: Shape(2) [static(0)]
      Outputs:
        constantofshape1_out1: F32[?, ?]
      Config:
        ConstantOfShapeConfig {
            shape: Static(
                [
                    2,
                    3,
                ],
            ),
            value: Some(
                TensorData {
                    bytes: Bytes {
                        data: [
                            0,
                            0,
                            128,
                            "...",
                        ],
                        len: 4,
                    },
                    shape: Shape {
                        dims: [
                            1,
                        ],
                    },
                    dtype: F32,
                },
            ),
        }
    "#);
}

#[rstest]
fn dequantize_linear(graph: &OnnxGraph) {
    let node = find_node(graph, "dequantizelinear");
    insta::assert_snapshot!(format!("{node}"), @r#"
    DequantizeLinear "dequantizelinear1"
      Inputs:
        dequantizelinear_input: U8[2, 3]
        constant2_out1: ScalarTensor(F32) [constant]
        constant3_out1: ScalarTensor(U8) [constant]
      Outputs:
        dequantizelinear1_out1: F32[2, 3]
      Config:
        DequantizeLinearConfig {
            axis: None,
            block_size: None,
            output_dtype: None,
        }
    "#);
}

#[rstest]
fn flatten(graph: &OnnxGraph) {
    let node = find_node(graph, "flatten");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Flatten "flatten1"
      Inputs:
        flatten_input: F32[2, 3, 4]
      Outputs:
        flatten1_out1: F32[2, 12]
      Config:
        FlattenConfig {
            axis: 1,
        }
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_24.onnx");
}

#[rstest]
fn if_op(graph: &OnnxGraph) {
    let node = find_node(graph, "if");
    insta::assert_snapshot!(format!("{node}"), @r#"
    If "if1"
      Inputs:
        if_condition: ScalarNative(Bool(Native))
      Outputs:
        if1_out1: F32[2, 3]
      Config:
        IfConfig {
            then_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant22",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant22_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant22_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant22_out1": 0,
                        },
                    },
                ),
            },
            else_branch: OnnxGraph {
                nodes: [
                    Constant(
                        ConstantNode {
                            name: "constant23",
                            inputs: [
                                Argument {
                                    name: "",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Static(
                                        0,
                                    ),
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "constant23_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Constant,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [],
                outputs: [
                    Argument {
                        name: "constant23_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Constant,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {
                                0: TensorDataRef {
                                    shape: [
                                        2,
                                        3,
                                    ],
                                    dtype: F32,
                                    source: Embedded(
                                        b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
                                    ),
                                },
                            },
                            next_id: 1,
                        },
                        constant_map: {
                            "constant23_out1": 0,
                        },
                    },
                ),
            },
            scope_ref_names: [],
        }
    "#);
}

#[rstest]
fn loop_op(graph: &OnnxGraph) {
    let node = find_node(graph, "loop");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Loop "loop1"
      Inputs:
        constant4_out1: ScalarNative(I64) [constant]
        constant5_out1: ScalarNative(Bool(Native)) [constant]
        loop_acc: F32[2, 3]
      Outputs:
        loop1_out1: F32[2, 3]
      Config:
        LoopConfig {
            body: OnnxGraph {
                nodes: [
                    Add(
                        AddNode {
                            name: "add4",
                            inputs: [
                                Argument {
                                    name: "loop_acc_in",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                                Argument {
                                    name: "loop_acc_in",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "add4_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 2,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                    Some(
                                                        3,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [
                    Argument {
                        name: "loop_iter",
                        ty: ScalarNative(
                            I64,
                        ),
                        value_source: Dynamic,
                    },
                    Argument {
                        name: "loop_cond_in",
                        ty: ScalarNative(
                            Bool(
                                Native,
                            ),
                        ),
                        value_source: Dynamic,
                    },
                    Argument {
                        name: "loop_acc_in",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                ],
                outputs: [
                    Argument {
                        name: "loop_cond_in",
                        ty: ScalarNative(
                            Bool(
                                Native,
                            ),
                        ),
                        value_source: Dynamic,
                    },
                    Argument {
                        name: "add4_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 2,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                        Some(
                                            3,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {},
                            next_id: 0,
                        },
                        constant_map: {},
                    },
                ),
            },
            scope_ref_names: [],
        }
    "#);
}

#[rstest]
fn pad(graph: &OnnxGraph) {
    let node = find_node(graph, "pad");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Pad "pad1"
      Inputs:
        pad_input: F32[2, 3]
        _: I64[4] [static(5)]
        _: ScalarNative(F32) [static(6)]
      Outputs:
        pad1_out1: F32[2, 3]
      Config:
        PadConfig {
            pads: Static(
                [
                    (
                        0,
                        0,
                    ),
                    (
                        1,
                        1,
                    ),
                ],
            ),
            constant_value: Static(
                0.0,
            ),
            mode: Constant,
        }
    "#);
}

#[rstest]
fn quantize_linear(graph: &OnnxGraph) {
    let node = find_node(graph, "quantizelinear");
    insta::assert_snapshot!(format!("{node}"), @r#"
    QuantizeLinear "quantizelinear1"
      Inputs:
        quantizelinear_input: F32[2, 3]
        constant8_out1: ScalarTensor(F32) [constant]
        constant9_out1: ScalarTensor(U8) [constant]
      Outputs:
        quantizelinear1_out1: U8[2, 3]
      Config:
        QuantizeLinearConfig {
            axis: None,
            block_size: None,
            output_dtype: None,
            precision: None,
            saturate: None,
        }
    "#);
}

#[rstest]
fn reshape(graph: &OnnxGraph) {
    let node = find_node(graph, "reshape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Reshape "reshape1"
      Inputs:
        reshape_input: F32[2, 3, 4]
        _: I64[2] [static(9)]
      Outputs:
        reshape1_out1: F32[6, 4]
      Config:
        ReshapeConfig {
            shape: Static(
                [
                    6,
                    4,
                ],
            ),
        }
    "#);
}

#[rstest]
fn scan(graph: &OnnxGraph) {
    let node = find_node(graph, "scan");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Scan "scan1"
      Inputs:
        scan_init: F32[2]
        scan_seq: F32[3, 2]
      Outputs:
        scan1_out1: F32[2]
        scan1_out2: F32[?, ?]
      Config:
        ScanConfig {
            body: OnnxGraph {
                nodes: [
                    Add(
                        AddNode {
                            name: "add4",
                            inputs: [
                                Argument {
                                    name: "scan_sum_in",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 1,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                                Argument {
                                    name: "scan_elem",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 1,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                            ],
                            outputs: [
                                Argument {
                                    name: "add4_out1",
                                    ty: Tensor(
                                        TensorType {
                                            dtype: F32,
                                            rank: 1,
                                            static_shape: Some(
                                                [
                                                    Some(
                                                        2,
                                                    ),
                                                ],
                                            ),
                                        },
                                    ),
                                    value_source: Dynamic,
                                },
                            ],
                        },
                    ),
                ],
                inputs: [
                    Argument {
                        name: "scan_sum_in",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 1,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                    Argument {
                        name: "scan_elem",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 1,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                ],
                outputs: [
                    Argument {
                        name: "add4_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 1,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                    Argument {
                        name: "add4_out1",
                        ty: Tensor(
                            TensorType {
                                dtype: F32,
                                rank: 1,
                                static_shape: Some(
                                    [
                                        Some(
                                            2,
                                        ),
                                    ],
                                ),
                            },
                        ),
                        value_source: Dynamic,
                    },
                ],
                value_store: Some(
                    ValueStore {
                        tensor_store: TensorStore {
                            data: {},
                            next_id: 0,
                        },
                        constant_map: {},
                    },
                ),
            },
            num_scan_inputs: 1,
            scan_input_directions: [],
            scan_output_directions: [],
            scan_input_axes: [],
            scan_output_axes: [],
            scope_ref_names: [],
        }
    "#);
}

#[rstest]
fn shape(graph: &OnnxGraph) {
    let node = find_node(graph, "shape");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Shape "shape1"
      Inputs:
        shape_input: F32[2, 3, 4]
      Outputs:
        shape1_out1: Shape(3)
      Config:
        ShapeConfig {
            start: 0,
            end: 3,
        }
    "#);
}

#[rstest]
fn size(graph: &OnnxGraph) {
    let node = find_node(graph, "size");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Size "size1"
      Inputs:
        size_input: F32[2, 3, 4]
      Outputs:
        size1_out1: ScalarNative(I64)
    "#);
}

#[rstest]
fn squeeze(graph: &OnnxGraph) {
    let node = find_node(graph, "squeeze");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Squeeze "squeeze1"
      Inputs:
        squeeze_input: F32[1, 3, 1, 4]
        _: I64[2] [static(10)]
      Outputs:
        squeeze1_out1: F32[3, 4]
      Config:
        SqueezeConfig {
            axes: Some(
                Static(
                    [
                        0,
                        2,
                    ],
                ),
            ),
        }
    "#);
}

#[rstest]
fn swish(graph: &OnnxGraph) {
    let node = find_node(graph, "swish");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Swish "swish1"
      Inputs:
        swish_input: F32[2, 3, 4]
      Outputs:
        swish1_out1: F32[2, 3, 4]
      Config:
        SwishConfig {
            alpha: 1.0,
        }
    "#);
}

#[rstest]
fn top_k(graph: &OnnxGraph) {
    let node = find_node(graph, "topk");
    insta::assert_snapshot!(format!("{node}"), @r#"
    TopK "topk1"
      Inputs:
        topk_input: F32[3, 4]
        _: I64[1] [static(11)]
      Outputs:
        topk1_out1: F32[?, ?]
        topk1_out2: I64[?, ?]
      Config:
        TopKConfig {
            axis: 1,
            k: Static(
                2,
            ),
            largest: true,
            sorted: true,
        }
    "#);
}

#[rstest]
fn transpose(graph: &OnnxGraph) {
    let node = find_node(graph, "transpose");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Transpose "transpose1"
      Inputs:
        transpose_input: F32[2, 3, 4]
      Outputs:
        transpose1_out1: F32[4, 3, 2]
      Config:
        TransposeConfig {
            perm: [
                2,
                1,
                0,
            ],
        }
    "#);
}

#[rstest]
fn unsqueeze(graph: &OnnxGraph) {
    let node = find_node(graph, "unsqueeze");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Unsqueeze "unsqueeze1"
      Inputs:
        unsqueeze_input: F32[3, 4]
        _: I64[2] [static(12)]
      Outputs:
        unsqueeze1_out1: F32[1, 3, 4, 1]
      Config:
        Static(
            [
                0,
                3,
            ],
        )
    "#);
}
