//! Opset 14 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn add() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "add");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Add(
        AddNode {
            name: "add1",
            inputs: [
                Argument {
                    name: "add_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "add_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "add1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn batch_normalization() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "batchnormalization");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    BatchNormalization(
        BatchNormalizationNode {
            name: "batchnormalization1",
            inputs: [
                Argument {
                    name: "batchnormalization_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        2,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        3,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "batchnormalization1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: Static(
                BatchNormStaticConfig {
                    epsilon: 0.0,
                    momentum: 0.0,
                },
            ),
        },
    )
    "#);
}

#[test]
fn cum_sum() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "cumsum");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    CumSum(
        CumSumNode {
            name: "cumsum1",
            inputs: [
                Argument {
                    name: "cumsum_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Scalar(
                        I32,
                    ),
                    value_source: Static(
                        4,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "cumsum1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: CumSumConfig {
                axis: Static(
                    1,
                ),
                exclusive: false,
                reverse: false,
            },
        },
    )
    "#);
}

#[test]
fn div() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "div");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Div(
        DivNode {
            name: "div1",
            inputs: [
                Argument {
                    name: "div_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "div_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "div1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn gru() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "gru");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Gru(
        GruNode {
            name: "gru1",
            inputs: [
                Argument {
                    name: "gru_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        5,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        6,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "gru1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: GruConfig {
                input_size: 3,
                hidden_size: 4,
                direction: Forward,
                has_bias: false,
                has_initial_h: false,
                batch_first: false,
                clip: None,
                linear_before_reset: false,
                gate_activation: Sigmoid,
                hidden_activation: Tanh,
                activation_alpha: None,
                activation_beta: None,
            },
        },
    )
    "#);
}

#[test]
fn hard_swish() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "hardswish");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    HardSwish(
        HardSwishNode {
            name: "hardswish1",
            inputs: [
                Argument {
                    name: "hardswish_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "hardswish1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_14.onnx");
}

#[test]
fn lstm() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "lstm");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Lstm(
        LstmNode {
            name: "lstm1",
            inputs: [
                Argument {
                    name: "lstm_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        16,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        7,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        16,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        8,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "lstm1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: LstmConfig {
                input_size: 3,
                hidden_size: 4,
                direction: Forward,
                has_bias: false,
                has_initial_h: false,
                has_initial_c: false,
                has_peephole: false,
                batch_first: false,
                clip: None,
                input_forget: false,
                gate_activation: Sigmoid,
                cell_activation: Tanh,
                hidden_activation: Tanh,
            },
        },
    )
    "#);
}

#[test]
fn mul() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "mul");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Mul(
        MulNode {
            name: "mul1",
            inputs: [
                Argument {
                    name: "mul_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "mul_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "mul1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn relu() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "relu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Relu(
        ReluNode {
            name: "relu1",
            inputs: [
                Argument {
                    name: "relu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "relu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn reshape() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "reshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Reshape(
        ReshapeNode {
            name: "reshape1",
            inputs: [
                Argument {
                    name: "reshape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        9,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        6,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReshapeConfig {
                shape: Static(
                    [
                        6,
                        4,
                    ],
                ),
            },
        },
    )
    "#);
}

#[test]
fn sub() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "sub");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Sub(
        SubNode {
            name: "sub1",
            inputs: [
                Argument {
                    name: "sub_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "sub_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "sub1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn trilu() {
    let graph = load_model("opset_14.onnx");
    let node = find_node(&graph, "trilu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Trilu(
        TriluNode {
            name: "trilu1",
            inputs: [
                Argument {
                    name: "trilu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "trilu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: TriluConfig {
                upper: true,
                diagonal: 0,
            },
        },
    )
    "#);
}
