//! Opset 5 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn reshape() {
    let graph = load_model("opset_05.onnx");
    let node = find_node(&graph, "reshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Reshape(
        ReshapeNode {
            name: "reshape1",
            inputs: [
                Argument {
                    name: "reshape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        6,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReshapeConfig {
                shape: Static(
                    [
                        6,
                        4,
                    ],
                ),
            },
        },
    )
    "#);
}
