//! Opset 10 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;
use rstest::*;

#[fixture]
#[once]
fn graph() -> OnnxGraph {
    load_model("opset_10.onnx")
}

#[rstest]
fn average_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "averagepool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    AveragePool2d "averagepool2d1"
      Inputs:
        averagepool_input: F32[1, 3, 8, 8]
      Outputs:
        averagepool2d1_out1: F32[?, ?, ?, ?]
      Config:
        AvgPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            count_include_pad: false,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn average_pool1d(graph: &OnnxGraph) {
    let node = find_node(graph, "averagepool1d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    AveragePool1d "averagepool1d1"
      Inputs:
        averagepool1d_input: F32[1, 3, 8]
      Outputs:
        averagepool1d1_out1: F32[?, ?, ?]
      Config:
        AvgPool1dConfig {
            kernel_size: 2,
            stride: 2,
            padding: Valid,
            count_include_pad: false,
            dilation: 1,
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn average_pool3d(graph: &OnnxGraph) {
    let node = find_node(graph, "averagepool3d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    AveragePool3d "averagepool3d1"
      Inputs:
        averagepool3d_input: F32[1, 3, 8, 8, 8]
      Outputs:
        averagepool3d1_out1: F32[?, ?, ?, ?, ?]
      Config:
        AvgPool3dConfig {
            kernel_size: [
                2,
                2,
                2,
            ],
            strides: [
                2,
                2,
                2,
            ],
            padding: Valid,
            count_include_pad: false,
            dilation: [
                1,
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn dequantize_linear(graph: &OnnxGraph) {
    let node = find_node(graph, "dequantizelinear");
    insta::assert_snapshot!(format!("{node}"), @r#"
    DequantizeLinear "dequantizelinear1"
      Inputs:
        dequantizelinear_input: U8[2, 3]
        constant1_out1: ScalarTensor(F32) [constant]
        constant2_out1: ScalarTensor(U8) [constant]
      Outputs:
        dequantizelinear1_out1: F32[2, 3]
      Config:
        DequantizeLinearConfig {
            axis: None,
            block_size: None,
            output_dtype: None,
        }
    "#);
}

/// Dropout is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn dropout() {
    let _graph = load_model("opset_10.onnx");
}

#[rstest]
fn is_inf(graph: &OnnxGraph) {
    let node = find_node(graph, "isinf");
    insta::assert_snapshot!(format!("{node}"), @r#"
    IsInf "isinf1"
      Inputs:
        isinf_input: F32[2, 3]
      Outputs:
        isinf1_out1: Bool(Native)[2, 3]
      Config:
        IsInfConfig {
            detect_negative: true,
            detect_positive: true,
        }
    "#);
}

#[rstest]
fn mat_mul_integer(graph: &OnnxGraph) {
    let node = find_node(graph, "matmulinteger");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MatMulInteger "matmulinteger1"
      Inputs:
        matmulinteger_a: U8[2, 3]
        matmulinteger_b: U8[3, 4]
      Outputs:
        matmulinteger1_out1: I32[?, ?]
    "#);
}

#[rstest]
fn max_pool(graph: &OnnxGraph) {
    let node = find_node(graph, "maxpool2d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MaxPool2d "maxpool2d1"
      Inputs:
        maxpool_input: F32[1, 3, 8, 8]
      Outputs:
        maxpool2d1_out1: F32[1, 3, 8, 8]
      Config:
        MaxPool2dConfig {
            kernel_size: [
                2,
                2,
            ],
            strides: [
                2,
                2,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
            storage_order: 0,
        }
    "#);
}

#[rstest]
fn max_pool1d(graph: &OnnxGraph) {
    let node = find_node(graph, "maxpool1d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MaxPool1d "maxpool1d1"
      Inputs:
        maxpool1d_input: F32[1, 3, 8]
      Outputs:
        maxpool1d1_out1: F32[1, 3, 8]
      Config:
        MaxPool1dConfig {
            kernel_size: 2,
            stride: 2,
            dilation: 1,
            padding: Valid,
            ceil_mode: false,
            auto_pad: NotSet,
            storage_order: 0,
        }
    "#);
}

#[rstest]
fn max_pool3d(graph: &OnnxGraph) {
    let node = find_node(graph, "maxpool3d");
    insta::assert_snapshot!(format!("{node}"), @r#"
    MaxPool3d "maxpool3d1"
      Inputs:
        maxpool3d_input: F32[1, 3, 8, 8, 8]
      Outputs:
        maxpool3d1_out1: F32[1, 3, 8, 8, 8]
      Config:
        MaxPool3dConfig {
            kernel_size: [
                2,
                2,
                2,
            ],
            strides: [
                2,
                2,
                2,
            ],
            padding: Valid,
            dilation: [
                1,
                1,
                1,
            ],
            ceil_mode: false,
            auto_pad: NotSet,
        }
    "#);
}

#[rstest]
fn mod_op(graph: &OnnxGraph) {
    let node = find_node(graph, "mod");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Mod "mod1"
      Inputs:
        mod_a: F32[2, 3, 4]
        mod_b: F32[2, 3, 4]
      Outputs:
        mod1_out1: F32[2, 3, 4]
      Config:
        ModConfig {
            fmod: false,
        }
    "#);
}

#[rstest]
fn non_max_suppression(graph: &OnnxGraph) {
    let node = find_node(graph, "nonmaxsuppression");
    insta::assert_snapshot!(format!("{node}"), @r#"
    NonMaxSuppression "nonmaxsuppression1"
      Inputs:
        nonmaxsuppression_boxes: F32[1, 4, 4]
        nonmaxsuppression_scores: F32[1, 1, 4]
        constant3_out1: I64[1] [constant]
        constant4_out1: F32[1] [constant]
      Outputs:
        nonmaxsuppression1_out1: I64[?, 3]
      Config:
        NonMaxSuppressionConfig {
            center_point_box: None,
        }
    "#);
}

#[rstest]
fn q_linear_mat_mul(graph: &OnnxGraph) {
    let node = find_node(graph, "qlinearmatmul");
    insta::assert_snapshot!(format!("{node}"), @r#"
    QLinearMatMul "qlinearmatmul1"
      Inputs:
        qlinearmatmul_a: U8[2, 3]
        constant5_out1: ScalarTensor(F32) [constant]
        constant6_out1: ScalarTensor(U8) [constant]
        qlinearmatmul_b: U8[3, 4]
        constant7_out1: ScalarTensor(F32) [constant]
        constant8_out1: ScalarTensor(U8) [constant]
        constant9_out1: ScalarTensor(F32) [constant]
        constant10_out1: ScalarTensor(U8) [constant]
      Outputs:
        qlinearmatmul1_out1: U8[?, ?]
    "#);
}

#[rstest]
fn quantize_linear(graph: &OnnxGraph) {
    let node = find_node(graph, "quantizelinear");
    insta::assert_snapshot!(format!("{node}"), @r#"
    QuantizeLinear "quantizelinear1"
      Inputs:
        quantizelinear_input: F32[2, 3]
        constant11_out1: ScalarTensor(F32) [constant]
        constant12_out1: ScalarTensor(U8) [constant]
      Outputs:
        quantizelinear1_out1: U8[2, 3]
      Config:
        QuantizeLinearConfig {
            axis: None,
            block_size: None,
            output_dtype: None,
            precision: None,
            saturate: None,
        }
    "#);
}

#[rstest]
fn resize(graph: &OnnxGraph) {
    let node = find_node(graph, "resize");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Resize "resize1"
      Inputs:
        resize_input: F32[1, 1, 2, 2]
        _: F32[4] [static(12)]
      Outputs:
        resize1_out1: F32[1, 1, 2, 2]
      Config:
        ResizeConfig {
            mode: Nearest,
            scales: Some(
                Static(
                    [
                        2.0,
                        2.0,
                    ],
                ),
            ),
            sizes: None,
            coordinate_transformation_mode: Asymmetric,
            cubic_coeff_a: -0.75,
            nearest_mode: RoundPreferFloor,
            exclude_outside: 0,
            extrapolation_value: 0.0,
            antialias: 0,
        }
    "#);
}

#[rstest]
fn slice(graph: &OnnxGraph) {
    let node = find_node(graph, "slice");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Slice "slice1"
      Inputs:
        slice_input: F32[4, 6]
        _: I64[2] [static(13)]
        _: I64[2] [static(14)]
        _: I64[2] [static(15)]
      Outputs:
        slice1_out1: F32[2, 3]
      Config:
        SliceConfig {
            starts: Static(
                [
                    0,
                    1,
                ],
            ),
            ends: Static(
                [
                    2,
                    4,
                ],
            ),
            axes: Some(
                Static(
                    [
                        0,
                        1,
                    ],
                ),
            ),
            steps: Some(
                Static(
                    [
                        1,
                        1,
                    ],
                ),
            ),
        }
    "#);
}

#[rstest]
fn thresholded_relu(graph: &OnnxGraph) {
    let node = find_node(graph, "thresholdedrelu");
    insta::assert_snapshot!(format!("{node}"), @r#"
    ThresholdedRelu "thresholdedrelu1"
      Inputs:
        thresholdedrelu_input: F32[2, 3, 4]
      Outputs:
        thresholdedrelu1_out1: F32[2, 3, 4]
      Config:
        ThresholdedReluConfig {
            alpha: 1.0,
        }
    "#);
}

#[rstest]
fn top_k(graph: &OnnxGraph) {
    let node = find_node(graph, "topk");
    insta::assert_snapshot!(format!("{node}"), @r#"
    TopK "topk1"
      Inputs:
        topk_input: F32[3, 4]
        _: I64[1] [static(16)]
      Outputs:
        topk1_out1: F32[?, ?]
        topk1_out2: I64[?, ?]
      Config:
        TopKConfig {
            axis: 1,
            k: Static(
                2,
            ),
            largest: true,
            sorted: true,
        }
    "#);
}

#[rstest]
fn upsample(graph: &OnnxGraph) {
    let node = find_node(graph, "upsample");
    insta::assert_snapshot!(format!("{node}"), @r#"
    Resize "upsample1"
      Inputs:
        upsample_input: F32[1, 1, 2, 2]
        _: F32[4] [static(17)]
      Outputs:
        upsample1_out1: F32[1, 1, 4, 4]
      Config:
        ResizeConfig {
            mode: Nearest,
            scales: Some(
                Static(
                    [
                        2.0,
                        2.0,
                    ],
                ),
            ),
            sizes: None,
            coordinate_transformation_mode: Asymmetric,
            cubic_coeff_a: -0.75,
            nearest_mode: Floor,
            exclude_outside: 0,
            extrapolation_value: 0.0,
            antialias: 0,
        }
    "#);
}
