//! Opset 3 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn gru() {
    let graph = load_model("opset_03.onnx");
    let node = find_node(&graph, "gru");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Gru(
        GruNode {
            name: "gru1",
            inputs: [
                Argument {
                    name: "gru_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        12,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "gru1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: GruConfig {
                input_size: 3,
                hidden_size: 4,
                direction: Forward,
                has_bias: false,
                has_initial_h: false,
                batch_first: false,
                clip: None,
                linear_before_reset: false,
                gate_activation: Sigmoid,
                hidden_activation: Tanh,
                activation_alpha: None,
                activation_beta: None,
            },
        },
    )
    "#);
}
