//! Opset 20 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn constant_of_shape() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "constantofshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ConstantOfShape(
        ConstantOfShapeNode {
            name: "constantofshape1",
            inputs: [
                Argument {
                    name: "",
                    ty: Shape(
                        2,
                    ),
                    value_source: Static(
                        0,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "constantofshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ConstantOfShapeConfig {
                shape: Static(
                    [
                        2,
                        3,
                    ],
                ),
                value: Some(
                    TensorData {
                        bytes: Bytes {
                            data: [
                                0,
                                0,
                                128,
                                "...",
                            ],
                            len: 4,
                        },
                        shape: [
                            1,
                        ],
                        dtype: F32,
                    },
                ),
            },
        },
    )
    "#);
}

#[test]
fn gelu() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "gelu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Gelu(
        GeluNode {
            name: "gelu1",
            inputs: [
                Argument {
                    name: "gelu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "gelu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn grid_sample() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "gridsample");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    GridSample(
        GridSampleNode {
            name: "gridsample1",
            inputs: [
                Argument {
                    name: "gridsample_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "gridsample_grid",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "gridsample1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: GridSampleConfig {
                mode: Bilinear,
                padding_mode: Zeros,
                align_corners: false,
            },
        },
    )
    "#);
}

#[test]
fn is_inf() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "isinf");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    IsInf(
        IsInfNode {
            name: "isinf1",
            inputs: [
                Argument {
                    name: "isinf_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "isinf1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: Bool,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: IsInfConfig {
                detect_negative: true,
                detect_positive: true,
            },
        },
    )
    "#);
}

#[test]
fn is_na_n() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "isnan");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    IsNaN(
        IsNaNNode {
            name: "isnan1",
            inputs: [
                Argument {
                    name: "isnan_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "isnan1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: Bool,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn reduce_max() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "reducemax");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ReduceMax(
        ReduceMaxNode {
            name: "reducemax1",
            inputs: [
                Argument {
                    name: "reducemax_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reducemax1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReduceConfig {
                dims: [
                    1,
                ],
                keepdims: true,
            },
        },
    )
    "#);
}

#[test]
fn reduce_min() {
    let graph = load_model("opset_20.onnx");
    let node = find_node(&graph, "reducemin");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ReduceMin(
        ReduceMinNode {
            name: "reducemin1",
            inputs: [
                Argument {
                    name: "reducemin_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        2,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reducemin1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReduceConfig {
                dims: [
                    1,
                ],
                keepdims: true,
            },
        },
    )
    "#);
}
