//! Opset 6 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn abs() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "abs");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Abs(
        AbsNode {
            name: "abs1",
            inputs: [
                Argument {
                    name: "abs_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "abs1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn cast() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "cast");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Cast(
        CastNode {
            name: "cast1",
            inputs: [
                Argument {
                    name: "cast_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "cast1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: I32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: CastConfig {
                to: I32,
            },
        },
    )
    "#);
}

#[test]
fn ceil() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "ceil");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Ceil(
        CeilNode {
            name: "ceil1",
            inputs: [
                Argument {
                    name: "ceil_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "ceil1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn clip() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "clip");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Clip(
        ClipNode {
            name: "clip1",
            inputs: [
                Argument {
                    name: "clip_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "clip1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ClipConfig {
                min: Some(
                    Static(
                        0.0,
                    ),
                ),
                max: Some(
                    Static(
                        6.0,
                    ),
                ),
            },
        },
    )
    "#);
}

/// Dropout is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn dropout() {
    let _graph = load_model("opset_06.onnx");
}

#[test]
fn elu() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "elu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Elu(
        EluNode {
            name: "elu1",
            inputs: [
                Argument {
                    name: "elu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "elu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: EluConfig {
                alpha: 1.0,
            },
        },
    )
    "#);
}

#[test]
fn exp() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "exp");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Exp(
        ExpNode {
            name: "exp1",
            inputs: [
                Argument {
                    name: "exp_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "exp1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn floor() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "floor");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Floor(
        FloorNode {
            name: "floor1",
            inputs: [
                Argument {
                    name: "floor_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "floor1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn hard_sigmoid() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "hardsigmoid");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    HardSigmoid(
        HardSigmoidNode {
            name: "hardsigmoid1",
            inputs: [
                Argument {
                    name: "hardsigmoid_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "hardsigmoid1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: HardSigmoidConfig {
                alpha: 0.2,
                beta: 0.5,
            },
        },
    )
    "#);
}

#[test]
fn instance_normalization() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "instancenormalization");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    InstanceNormalization(
        InstanceNormalizationNode {
            name: "instancenormalization1",
            inputs: [
                Argument {
                    name: "instancenormalization_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "instancenormalization1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: InstanceNormConfig {
                epsilon: 9.999999747378752e-6,
            },
        },
    )
    "#);
}

#[test]
fn leaky_relu() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "leakyrelu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    LeakyRelu(
        LeakyReluNode {
            name: "leakyrelu1",
            inputs: [
                Argument {
                    name: "leakyrelu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "leakyrelu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: LeakyReluConfig {
                alpha: 0.009999999776482582,
            },
        },
    )
    "#);
}

#[test]
fn log() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "log");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Log(
        LogNode {
            name: "log1",
            inputs: [
                Argument {
                    name: "log_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "log1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn max() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "max");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Max(
        MaxNode {
            name: "max1",
            inputs: [
                Argument {
                    name: "max_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "max_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "max1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn min() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "min");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Min(
        MinNode {
            name: "min1",
            inputs: [
                Argument {
                    name: "min_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "min_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "min1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn neg() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "neg");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Neg(
        NegNode {
            name: "neg1",
            inputs: [
                Argument {
                    name: "neg_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "neg1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn p_relu() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "prelu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    PRelu(
        PReluNode {
            name: "prelu1",
            inputs: [
                Argument {
                    name: "prelu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        2,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "prelu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn reciprocal() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "reciprocal");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Reciprocal(
        ReciprocalNode {
            name: "reciprocal1",
            inputs: [
                Argument {
                    name: "reciprocal_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "reciprocal1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn relu() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "relu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Relu(
        ReluNode {
            name: "relu1",
            inputs: [
                Argument {
                    name: "relu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "relu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn selu() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "selu");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Selu(
        SeluNode {
            name: "selu1",
            inputs: [
                Argument {
                    name: "selu_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "selu1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: SeluConfig {
                alpha: 1.6732631921768188,
                gamma: 1.0507010221481323,
            },
        },
    )
    "#);
}

#[test]
fn sigmoid() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "sigmoid");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Sigmoid(
        SigmoidNode {
            name: "sigmoid1",
            inputs: [
                Argument {
                    name: "sigmoid_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "sigmoid1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn sqrt() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "sqrt");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Sqrt(
        SqrtNode {
            name: "sqrt1",
            inputs: [
                Argument {
                    name: "sqrt_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "sqrt1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn tanh() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "tanh");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Tanh(
        TanhNode {
            name: "tanh1",
            inputs: [
                Argument {
                    name: "tanh_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "tanh1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn tile() {
    let graph = load_model("opset_06.onnx");
    let node = find_node(&graph, "tile");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Tile(
        TileNode {
            name: "tile1",
            inputs: [
                Argument {
                    name: "tile_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        3,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "tile1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: TileConfig {
                repeats: Static(
                    [
                        2,
                        3,
                    ],
                ),
            },
        },
    )
    "#);
}

/// Ops that require min_opset > 6: Add, BatchNormalization, Div, Gemm, Mean, Mul, Sub, Sum
#[test]
fn unsupported_ops_fail() {
    let result = load_model_result("opset_06_unsupported.onnx");
    assert!(
        result.is_err(),
        "expected parse failure for unsupported ops at opset 6"
    );
}
