//! Opset 19 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn average_pool() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "averagepool2d");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    AveragePool2d(
        AveragePool2dNode {
            name: "averagepool2d1",
            inputs: [
                Argument {
                    name: "averagepool_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        8,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "averagepool2d1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: AvgPool2dConfig {
                kernel_size: [
                    2,
                    2,
                ],
                strides: [
                    2,
                    2,
                ],
                padding: Valid,
                count_include_pad: false,
                dilation: [
                    1,
                    1,
                ],
                ceil_mode: false,
                auto_pad: NotSet,
            },
        },
    )
    "#);
}

#[test]
fn cast() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "cast");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Cast(
        CastNode {
            name: "cast1",
            inputs: [
                Argument {
                    name: "cast_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "cast1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: I32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: CastConfig {
                to: I32,
            },
        },
    )
    "#);
}

#[test]
fn constant() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "constant");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Constant(
        ConstantNode {
            name: "constant8",
            inputs: [
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        7,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "constant8_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Constant,
                },
            ],
        },
    )
    "#);
}

#[test]
fn deform_conv() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "deformconv");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    DeformConv(
        DeformConvNode {
            name: "deformconv1",
            inputs: [
                Argument {
                    name: "deformconv_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        0,
                    ),
                },
                Argument {
                    name: "deformconv_offset",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        8,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "deformconv1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: DeformConvConfig {
                kernel_size: [
                    2,
                    2,
                ],
                stride: [
                    1,
                    1,
                ],
                padding: Valid,
                dilation: [
                    1,
                    1,
                ],
                groups: 1,
                offset_groups: 1,
            },
        },
    )
    "#);
}

#[test]
fn equal() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "equal");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Equal(
        EqualNode {
            name: "equal1",
            inputs: [
                Argument {
                    name: "equal_a",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "equal_b",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "equal1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: Bool,
                            rank: 3,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_19.onnx");
}

#[test]
fn if_op() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "if");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    If(
        IfNode {
            name: "if1",
            inputs: [
                Argument {
                    name: "if_condition",
                    ty: Scalar(
                        Bool,
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "if1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: IfConfig {
                then_branch: OnnxGraph {
                    nodes: [
                        Constant(
                            ConstantNode {
                                name: "constant12",
                                inputs: [
                                    Argument {
                                        name: "",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Static(
                                            0,
                                        ),
                                    },
                                ],
                                outputs: [
                                    Argument {
                                        name: "constant12_out1",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Constant,
                                    },
                                ],
                            },
                        ),
                    ],
                    inputs: [],
                    outputs: [
                        Argument {
                            name: "constant12_out1",
                            ty: Tensor(
                                TensorType {
                                    dtype: F32,
                                    rank: 2,
                                    static_shape: Some(
                                        [
                                            Some(
                                                2,
                                            ),
                                            Some(
                                                3,
                                            ),
                                        ],
                                    ),
                                },
                            ),
                            value_source: Constant,
                        },
                    ],
                    value_store: Some(
                        ValueStore {
                            tensor_store: TensorStore {
                                data: {
                                    0: TensorDataRef {
                                        shape: [
                                            2,
                                            3,
                                        ],
                                        dtype: F32,
                                        source: Embedded(
                                            b"\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?",
                                        ),
                                    },
                                },
                                next_id: 1,
                            },
                            constant_map: {
                                "constant12_out1": 0,
                            },
                        },
                    ),
                },
                else_branch: OnnxGraph {
                    nodes: [
                        Constant(
                            ConstantNode {
                                name: "constant13",
                                inputs: [
                                    Argument {
                                        name: "",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Static(
                                            0,
                                        ),
                                    },
                                ],
                                outputs: [
                                    Argument {
                                        name: "constant13_out1",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Constant,
                                    },
                                ],
                            },
                        ),
                    ],
                    inputs: [],
                    outputs: [
                        Argument {
                            name: "constant13_out1",
                            ty: Tensor(
                                TensorType {
                                    dtype: F32,
                                    rank: 2,
                                    static_shape: Some(
                                        [
                                            Some(
                                                2,
                                            ),
                                            Some(
                                                3,
                                            ),
                                        ],
                                    ),
                                },
                            ),
                            value_source: Constant,
                        },
                    ],
                    value_store: Some(
                        ValueStore {
                            tensor_store: TensorStore {
                                data: {
                                    0: TensorDataRef {
                                        shape: [
                                            2,
                                            3,
                                        ],
                                        dtype: F32,
                                        source: Embedded(
                                            b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
                                        ),
                                    },
                                },
                                next_id: 1,
                            },
                            constant_map: {
                                "constant13_out1": 0,
                            },
                        },
                    ),
                },
                scope_ref_names: [],
            },
        },
    )
    "#);
}

#[test]
fn pad() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "pad");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Pad(
        PadNode {
            name: "pad1",
            inputs: [
                Argument {
                    name: "pad_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
                Argument {
                    name: "",
                    ty: Scalar(
                        F32,
                    ),
                    value_source: Static(
                        2,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "pad1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: PadConfig {
                pads: Static(
                    [
                        1,
                        1,
                        0,
                        0,
                    ],
                ),
                constant_value: Static(
                    0.0,
                ),
                mode: Constant,
            },
        },
    )
    "#);
}

#[test]
fn reshape() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "reshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Reshape(
        ReshapeNode {
            name: "reshape1",
            inputs: [
                Argument {
                    name: "reshape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        3,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        6,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReshapeConfig {
                shape: Static(
                    [
                        6,
                        4,
                    ],
                ),
            },
        },
    )
    "#);
}

#[test]
fn resize() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "resize");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Resize(
        ResizeNode {
            name: "resize1",
            inputs: [
                Argument {
                    name: "resize_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        0,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        4,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        0,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        5,
                    ),
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        6,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "resize1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ResizeConfig {
                mode: Nearest,
                scales: None,
                sizes: Some(
                    Static(
                        [
                            4,
                            4,
                        ],
                    ),
                ),
                coordinate_transformation_mode: "half_pixel",
                cubic_coeff_a: -0.75,
                nearest_mode: "round_prefer_floor",
                exclude_outside: 0,
                extrapolation_value: 0.0,
                antialias: 0,
            },
        },
    )
    "#);
}

#[test]
fn shape() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "shape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Shape(
        ShapeNode {
            name: "shape1",
            inputs: [
                Argument {
                    name: "shape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "shape1_out1",
                    ty: Shape(
                        3,
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ShapeConfig {
                start: 0,
                end: 3,
            },
        },
    )
    "#);
}

#[test]
fn size() {
    let graph = load_model("opset_19.onnx");
    let node = find_node(&graph, "size");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Size(
        SizeNode {
            name: "size1",
            inputs: [
                Argument {
                    name: "size_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "size1_out1",
                    ty: Scalar(
                        I64,
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}
