//! Opset 23 compliance tests.
//!
//! Auto-generated by gen_rust_tests.py. Edit the generator, not this file.

use super::helpers::*;

#[test]
fn cast() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "cast");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Cast(
        CastNode {
            name: "cast1",
            inputs: [
                Argument {
                    name: "cast_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "cast1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: I32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: CastConfig {
                to: I32,
            },
        },
    )
    "#);
}

#[test]
fn constant() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "constant");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Constant(
        ConstantNode {
            name: "constant7",
            inputs: [
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        6,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "constant7_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Constant,
                },
            ],
        },
    )
    "#);
}

#[test]
fn constant_of_shape() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "constantofshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    ConstantOfShape(
        ConstantOfShapeNode {
            name: "constantofshape1",
            inputs: [
                Argument {
                    name: "",
                    ty: Shape(
                        2,
                    ),
                    value_source: Static(
                        0,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "constantofshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: None,
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ConstantOfShapeConfig {
                shape: Static(
                    [
                        2,
                        3,
                    ],
                ),
                value: Some(
                    TensorData {
                        bytes: Bytes {
                            data: [
                                0,
                                0,
                                128,
                                "...",
                            ],
                            len: 4,
                        },
                        shape: [
                            1,
                        ],
                        dtype: F32,
                    },
                ),
            },
        },
    )
    "#);
}

#[test]
fn flatten() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "flatten");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Flatten(
        FlattenNode {
            name: "flatten1",
            inputs: [
                Argument {
                    name: "flatten_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "flatten1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        12,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: FlattenConfig {
                axis: 1,
            },
        },
    )
    "#);
}

/// Identity is eliminated during post-processing (no-op).
/// Verify the model parses without error.
#[test]
fn identity() {
    let _graph = load_model("opset_23.onnx");
}

#[test]
fn if_op() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "if");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    If(
        IfNode {
            name: "if1",
            inputs: [
                Argument {
                    name: "if_condition",
                    ty: Scalar(
                        Bool,
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "if1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: IfConfig {
                then_branch: OnnxGraph {
                    nodes: [
                        Constant(
                            ConstantNode {
                                name: "constant11",
                                inputs: [
                                    Argument {
                                        name: "",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Static(
                                            0,
                                        ),
                                    },
                                ],
                                outputs: [
                                    Argument {
                                        name: "constant11_out1",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Constant,
                                    },
                                ],
                            },
                        ),
                    ],
                    inputs: [],
                    outputs: [
                        Argument {
                            name: "constant11_out1",
                            ty: Tensor(
                                TensorType {
                                    dtype: F32,
                                    rank: 2,
                                    static_shape: Some(
                                        [
                                            Some(
                                                2,
                                            ),
                                            Some(
                                                3,
                                            ),
                                        ],
                                    ),
                                },
                            ),
                            value_source: Constant,
                        },
                    ],
                    value_store: Some(
                        ValueStore {
                            tensor_store: TensorStore {
                                data: {
                                    0: TensorDataRef {
                                        shape: [
                                            2,
                                            3,
                                        ],
                                        dtype: F32,
                                        source: Embedded(
                                            b"\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?\0\0\x80?",
                                        ),
                                    },
                                },
                                next_id: 1,
                            },
                            constant_map: {
                                "constant11_out1": 0,
                            },
                        },
                    ),
                },
                else_branch: OnnxGraph {
                    nodes: [
                        Constant(
                            ConstantNode {
                                name: "constant12",
                                inputs: [
                                    Argument {
                                        name: "",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Static(
                                            0,
                                        ),
                                    },
                                ],
                                outputs: [
                                    Argument {
                                        name: "constant12_out1",
                                        ty: Tensor(
                                            TensorType {
                                                dtype: F32,
                                                rank: 2,
                                                static_shape: Some(
                                                    [
                                                        Some(
                                                            2,
                                                        ),
                                                        Some(
                                                            3,
                                                        ),
                                                    ],
                                                ),
                                            },
                                        ),
                                        value_source: Constant,
                                    },
                                ],
                            },
                        ),
                    ],
                    inputs: [],
                    outputs: [
                        Argument {
                            name: "constant12_out1",
                            ty: Tensor(
                                TensorType {
                                    dtype: F32,
                                    rank: 2,
                                    static_shape: Some(
                                        [
                                            Some(
                                                2,
                                            ),
                                            Some(
                                                3,
                                            ),
                                        ],
                                    ),
                                },
                            ),
                            value_source: Constant,
                        },
                    ],
                    value_store: Some(
                        ValueStore {
                            tensor_store: TensorStore {
                                data: {
                                    0: TensorDataRef {
                                        shape: [
                                            2,
                                            3,
                                        ],
                                        dtype: F32,
                                        source: Embedded(
                                            b"\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0",
                                        ),
                                    },
                                },
                                next_id: 1,
                            },
                            constant_map: {
                                "constant12_out1": 0,
                            },
                        },
                    ),
                },
                scope_ref_names: [],
            },
        },
    )
    "#);
}

#[test]
fn pad() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "pad");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Pad(
        PadNode {
            name: "pad1",
            inputs: [
                Argument {
                    name: "pad_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        1,
                    ),
                },
                Argument {
                    name: "",
                    ty: Scalar(
                        F32,
                    ),
                    value_source: Static(
                        2,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "pad1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: PadConfig {
                pads: Static(
                    [
                        1,
                        1,
                        0,
                        0,
                    ],
                ),
                constant_value: Static(
                    0.0,
                ),
                mode: Constant,
            },
        },
    )
    "#);
}

#[test]
fn reshape() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "reshape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Reshape(
        ReshapeNode {
            name: "reshape1",
            inputs: [
                Argument {
                    name: "reshape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        3,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "reshape1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        6,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ReshapeConfig {
                shape: Static(
                    [
                        6,
                        4,
                    ],
                ),
            },
        },
    )
    "#);
}

#[test]
fn shape() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "shape");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Shape(
        ShapeNode {
            name: "shape1",
            inputs: [
                Argument {
                    name: "shape_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "shape1_out1",
                    ty: Shape(
                        3,
                    ),
                    value_source: Dynamic,
                },
            ],
            config: ShapeConfig {
                start: 0,
                end: 3,
            },
        },
    )
    "#);
}

#[test]
fn size() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "size");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Size(
        SizeNode {
            name: "size1",
            inputs: [
                Argument {
                    name: "size_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "size1_out1",
                    ty: Scalar(
                        I64,
                    ),
                    value_source: Dynamic,
                },
            ],
        },
    )
    "#);
}

#[test]
fn squeeze() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "squeeze");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Squeeze(
        SqueezeNode {
            name: "squeeze1",
            inputs: [
                Argument {
                    name: "squeeze_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        4,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "squeeze1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: SqueezeConfig {
                axes: Some(
                    Static(
                        [
                            0,
                            2,
                        ],
                    ),
                ),
            },
        },
    )
    "#);
}

#[test]
fn transpose() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "transpose");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Transpose(
        TransposeNode {
            name: "transpose1",
            inputs: [
                Argument {
                    name: "transpose_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            outputs: [
                Argument {
                    name: "transpose1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 3,
                            static_shape: Some(
                                [
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: TransposeConfig {
                perm: [
                    2,
                    1,
                    0,
                ],
            },
        },
    )
    "#);
}

#[test]
fn unsqueeze() {
    let graph = load_model("opset_23.onnx");
    let node = find_node(&graph, "unsqueeze");
    insta::assert_snapshot!(format!("{node:#?}"), @r#"
    Unsqueeze(
        UnsqueezeNode {
            name: "unsqueeze1",
            inputs: [
                Argument {
                    name: "unsqueeze_input",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 2,
                            static_shape: Some(
                                [
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
                Argument {
                    name: "",
                    ty: Tensor(
                        TensorType {
                            dtype: I64,
                            rank: 1,
                            static_shape: Some(
                                [
                                    Some(
                                        2,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Static(
                        5,
                    ),
                },
            ],
            outputs: [
                Argument {
                    name: "unsqueeze1_out1",
                    ty: Tensor(
                        TensorType {
                            dtype: F32,
                            rank: 4,
                            static_shape: Some(
                                [
                                    Some(
                                        1,
                                    ),
                                    Some(
                                        3,
                                    ),
                                    Some(
                                        4,
                                    ),
                                    Some(
                                        1,
                                    ),
                                ],
                            ),
                        },
                    ),
                    value_source: Dynamic,
                },
            ],
            config: Static(
                [
                    0,
                    3,
                ],
            ),
        },
    )
    "#);
}
